#!/bin/bash

# Auto-Build Environment Setup for Spec 004
# Deploy danieltarazona.com to Cloudflare Pages with DNS Configuration
# Generated by Planner Agent

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;36m'
NC='\033[0m' # No Color

echo ""
echo "========================================"
echo "Spec 004: Cloudflare Pages Deployment"
echo "========================================"
echo ""

# ============================================
# PREREQUISITE CHECKS
# ============================================

echo -e "${BLUE}Checking prerequisites...${NC}"

# Check Node.js version
if ! command -v node &> /dev/null; then
    echo -e "${RED}ERROR: Node.js is not installed${NC}"
    echo "Please install Node.js >= 18.17.0"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2)
REQUIRED_VERSION="18.17.0"
if [ "$(printf '%s\n' "$REQUIRED_VERSION" "$NODE_VERSION" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]; then
    echo -e "${RED}ERROR: Node.js version $NODE_VERSION is too old${NC}"
    echo "Required: >= $REQUIRED_VERSION"
    exit 1
fi
echo -e "${GREEN}✓ Node.js $NODE_VERSION${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}ERROR: npm is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm $(npm -v)${NC}"

# Check dig (for DNS verification)
if ! command -v dig &> /dev/null; then
    echo -e "${YELLOW}⚠ dig not found - DNS verification commands may not work${NC}"
    echo "  Install: brew install bind (macOS) or apt install dnsutils (Linux)"
else
    echo -e "${GREEN}✓ dig available${NC}"
fi

# Check curl (for HTTP verification)
if ! command -v curl &> /dev/null; then
    echo -e "${YELLOW}⚠ curl not found - HTTP verification commands may not work${NC}"
else
    echo -e "${GREEN}✓ curl available${NC}"
fi

echo ""

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo -e "${BLUE}Installing dependencies...${NC}"
npm ci

if [ $? -ne 0 ]; then
    echo -e "${RED}ERROR: npm ci failed${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Dependencies installed${NC}"
echo ""

# ============================================
# TEST BUILD
# ============================================

echo -e "${BLUE}Testing production build...${NC}"
npm run build

if [ $? -ne 0 ]; then
    echo -e "${RED}ERROR: Build failed${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Build successful${NC}"
echo ""

# ============================================
# VERIFY BUILD OUTPUT
# ============================================

if [ ! -d "dist" ]; then
    echo -e "${RED}ERROR: dist/ directory not found after build${NC}"
    exit 1
fi

if [ ! -f "dist/index.html" ]; then
    echo -e "${RED}ERROR: dist/index.html not found${NC}"
    exit 1
fi

if [ ! -f "dist/sitemap.xml" ]; then
    echo -e "${YELLOW}⚠ dist/sitemap.xml not found - sitemap may not be generated${NC}"
else
    echo -e "${GREEN}✓ Sitemap generated${NC}"
fi

echo ""

# ============================================
# GITHUB SECRETS CHECK
# ============================================

echo -e "${BLUE}GitHub Secrets Verification${NC}"
echo ""
echo "Before proceeding, verify GitHub repository secrets are configured:"
echo ""
echo "  1. Go to: GitHub repository → Settings → Secrets and variables → Actions"
echo "  2. Verify these secrets exist:"
echo "     - CLOUDFLARE_API_TOKEN"
echo "     - CLOUDFLARE_ACCOUNT_ID"
echo ""
echo "If missing, obtain from Cloudflare Dashboard:"
echo "  - API Token: My Profile → API Tokens → Create Token (use 'Edit Cloudflare Workers' template)"
echo "  - Account ID: Workers & Pages → Account ID (right sidebar)"
echo ""

# ============================================
# DEPLOYMENT INFORMATION
# ============================================

echo ""
echo "========================================"
echo "Environment Ready for Deployment"
echo "========================================"
echo ""
echo "Project Details:"
echo "  - Framework: Astro v4.16.18"
echo "  - Build command: npm run build"
echo "  - Output directory: dist/"
echo "  - Production URL: https://danieltarazona.com"
echo "  - Cloudflare Pages project: danieltarazona-com"
echo ""
echo "Build Status:"
echo "  - Local build: ${GREEN}PASSED${NC}"
echo "  - dist/ directory: ${GREEN}EXISTS${NC}"
echo ""
echo "Next Steps:"
echo "  1. Verify GitHub secrets are configured (see above)"
echo "  2. Trigger GitHub Actions workflow:"
echo "     - Push to main/master branch, OR"
echo "     - GitHub Actions → deploy.yml → Run workflow"
echo "  3. Verify deployment at: https://danieltarazona-com.pages.dev"
echo "  4. Configure Cloudflare DNS (see implementation plan)"
echo "  5. Update Namecheap nameservers"
echo "  6. Wait for DNS propagation (24-48 hours)"
echo "  7. Verify site at: https://danieltarazona.com"
echo ""
echo "Verification Commands:"
echo "  # Check DNS nameservers"
echo "  dig danieltarazona.com NS +short"
echo ""
echo "  # Check DNS A record"
echo "  dig danieltarazona.com A +short"
echo ""
echo "  # Check HTTPS accessibility"
echo "  curl -I https://danieltarazona.com"
echo ""
echo "  # Check www redirect"
echo "  curl -I https://www.danieltarazona.com"
echo ""
echo "Useful Tools:"
echo "  - DNS Propagation: https://whatsmydns.net"
echo "  - DNS Checker: https://dnschecker.org"
echo "  - SSL Labs: https://www.ssllabs.com/ssltest/"
echo ""
echo "========================================"
echo "For detailed implementation steps, see:"
echo "  .auto-claude/specs/004-build-the-code-for-danieltarazona-com/implementation_plan.json"
echo "========================================"
echo ""
